# ___Tensorflow-2.0 in Action___

___Tensorflow2.0 is a combination design of Tensorflow1.x and Keras. Considering user feedback and framework development over the past four years, it largely solves the problems in TF 1.x and will become the future machine learning platform.___

_Tensorflow 2.0 is built on the following core ideas:_

* _The coding is more __pythonic__, so that users can get the results immediately like they are programming in numpy_
* _Retaining the characteristics of static graphs (for performance, distributed, and production deployment), this makes TensorFlow __fast, scalable, and ready for production__._
* _Using __Keras as a high-level API__ for deep learning, making Tensorflow easy to use and efficient_
* _Make the entire framework both high-level features (easy to use, efficient, and not flexible) and low-level features (powerful and scalable, not easy to use, but very flexible)_
* ___Eager execution___ _is by default in TensorFlow 2.0 and, it needs no special setup. The following below code can be used to find out whether a CPU or GPU is in use_

___Eager execution is a flexible machine learning platform for research and experimentation, providing:___

_TensorFlow's eager execution is an imperative programming environment that evaluates operations immediately, without building graphs: operations return concrete values instead of constructing a computational graph to run later._

* _An __intuitive interface__—Structure your code naturally and use Python data structures. Quickly iterate on small models and small data._
* ___Easier debugging___ _—Call ops directly to inspect running models and test changes. Use standard Python debugging tools for immediate error reporting._
* ___Natural control flow___ _—Use Python control flow instead of graph control flow, simplifying the specification of dynamic models._
* _Eager execution supports most TensorFlow operations and GPU acceleration._

### ___Installing Latest Version___

`pip install tensorflow`

In [1]:
import tensorflow as tf

print("TensorFlow version: {}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.3.0
Keras version: 2.4.0


### ___Tensor Constant___

In [2]:
constant = tf.constant(42)
constant

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [3]:
# To print the value
constant.numpy()

42

In [4]:
# constant with data type
constant = tf.constant(1, dtype = tf.int64)
constant

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [5]:
# Defining a matrix
constant = tf.constant([[4,2],[9,5]])
print(constant)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [6]:
constant.numpy()

array([[4, 2],
       [9, 5]], dtype=int32)

In [7]:
print('shape:',constant.shape)
print(constant.dtype)

shape: (2, 2)
<dtype: 'int32'>


#### ___tf.ones and tf.zeros like of numpy - np.ones & np.zeros___

In [8]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [9]:
print(tf.zeros(shape=(3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [10]:
const2 = tf.constant([[3,4,5], [3,4,5]]);
const1 = tf.constant([[1,2,3], [1,2,3]]);
result = tf.add(const1, const2);
print(result)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)


In [11]:
result.numpy()

array([[4, 6, 8],
       [4, 6, 8]], dtype=int32)

#### ___Random constant___

In [12]:
# Random Variables with Normal Distribution

tf.random.normal(shape=(2,2), mean=0, stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.5365436 ,  0.67560637],
       [-0.414258  , -1.0994934 ]], dtype=float32)>

In [13]:
# Random Uniform Distributions

tf.random.uniform(shape=(2,2), minval=0, maxval=10, dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 3],
       [6, 7]], dtype=int32)>

### ___Variables___

_A variable is a special tensor that is used to store variable values ​​and needs to be initialized with some values._

#### ___Declaring Variables___

In [14]:
var0 = 24 # python variable

var1 = tf.Variable(42) # rank 0 tensor

var2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) #rank 3 tensor

var0, var1, var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

_TensorFlow will infer the datatype, defaulting to tf.float32 for floats and tf.int32 for integers._

___The datatype can be explicitly specified:___

In [15]:
float_var64 = tf.Variable(89, dtype = tf.float64)
float_var64.dtype

tf.float64

#### ___Datatypes in TF 2.x___

* _tf.float16: 16-bit half-precision floating-point._
* _tf.float32: 32-bit single-precision floating-point._
* _tf.float64: 64-bit double-precision floating-point._
* _tf.bfloat16: 16-bit truncated floating-point._
* _tf.complex64: 64-bit single-precision complex._
* _tf.complex128: 128-bit double-precision complex._
* _tf.int8: 8-bit signed integer._
* _tf.uint8: 8-bit unsigned integer._
* _tf.uint16: 16-bit unsigned integer._
* _tf.uint32: 32-bit unsigned integer._
* _tf.uint64: 64-bit unsigned integer._
* _tf.int16: 16-bit signed integer._
* _tf.int32: 32-bit signed integer._
* _tf.int64: 64-bit signed integer._
* _tf.bool: Boolean._
* _tf.string: String._
* _tf.qint8: Quantized 8-bit signed integer._
* _tf.quint8: Quantized 8-bit unsigned integer._
* _tf.qint16: Quantized 16-bit signed integer._
* _tf.quint16: Quantized 16-bit unsigned integer._
* _tf.qint32: Quantized 32-bit signed integer._
* _tf.resource: Handle to a mutable resource._
* _tf.variant: Values of arbitrary types._


#### ___Reassign value to a variable, use var.assign()___

In [16]:
var_reassign = tf.Variable(89.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [17]:
# Reassigning a value

var_reassign.assign(98.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

In [18]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 2.5881362 ,  1.6461525 ],
       [-0.17538707,  1.3586714 ]], dtype=float32)>


_We can assign "=" with assign (value), or assign_add (value) with "+ =", or assign_sub (value) with "-="_

In [19]:
new_value = tf.random.normal(shape=(2, 2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j]

In [20]:
a.numpy()

array([[-1.5438577 ,  1.338098  ],
       [ 0.8550197 ,  0.00755402]], dtype=float32)

In [21]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j]+added_value[i,j]

a.numpy()        

array([[-0.39908493,  1.0237242 ],
       [ 0.8378687 ,  0.5914892 ]], dtype=float32)

### ___Shaping a Tensor___

In [22]:
tensor = tf.Variable([ [ [10., 11., 12.], [13., 14., 15.] ], [ [16., 17., 18.], [19., 20., 21.] ] ]) # tensor variable
print(tensor.shape)

(2, 2, 3)


In [23]:
tensor1 = tf.reshape(tensor,[2,6]) # 2 rows 6 cols
tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)>

In [24]:
tensor2 = tf.reshape(tensor,[1,12]) # 1 row 12 columns
tensor2

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21.]],
      dtype=float32)>

### ___Rank of a Tensor___

_The rank of a tensor is defined as the number of dimensions, which is the number of indices that are required to specify any particular element of that tensor._

In [25]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

#### ___Specifying an element of a tensor___

In [26]:
tensor3 = tensor[1, 0, 2] # slice 1, row 0, column 2
tensor3

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

### ___Casting a Tensor to Another Datatype___

In [35]:
i = tf.cast(tensor1, dtype=tf.int32)
i

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]], dtype=int32)>

#### ___Casting with Truncation___

In [ ]:
j = tf.cast(tf.constant(4.9), dtype=tf.int32)
j

<tf.Tensor: id=244, shape=(), dtype=int32, numpy=4>

#### ___Casting a tensor to a NumPy Variable___

In [27]:
print(tensor.numpy())

[[[10. 11. 12.]
  [13. 14. 15.]]

 [[16. 17. 18.]
  [19. 20. 21.]]]


In [28]:
print(tensor[1, 0, 2].numpy())

18.0


### ___Finding the Size or Length of a Tensor___

In [29]:
tensor_size = tf.size(input=tensor).numpy()
tensor_size

12

In [30]:
#the datatype of a tensor
tensor3.dtype

tf.float32

### ___Ragged Tensors___

_A ragged tensor is a tensor having one or more ragged dimensions. Ragged dimensions are dimensions that have slices having various lengths.There are a variety of methods for the declaration of ragged arrays, the simplest way is declaring a constant ragged array._

In [36]:
ragged =tf.ragged.constant([[9, 7, 4, 3], [], [11, 12, 8], [3], [7,8]])
print(ragged)

print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[9, 7, 4, 3], [], [11, 12, 8], [3], [7, 8]]>
tf.Tensor([9 7 4 3], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([11 12  8], shape=(3,), dtype=int32)
tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([7 8], shape=(2,), dtype=int32)


### ___Broadcasting in Tensorflow___

* _Element-wise tensor operations support broadcasting in the same way that NumPy arrays do._

* _The simplest example is multiplication of  a tensor by a scalar value._

_The term __Broadcasting__ refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed._

_If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes._

In [33]:
tensor4 = tensor*4
print(tensor4)

tf.Tensor(
[[[40. 44. 48.]
  [52. 56. 60.]]

 [[64. 68. 72.]
  [76. 80. 84.]]], shape=(2, 2, 3), dtype=float32)


### ___Tensorflow Mathematical Operations___

In [31]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))

c = a + b

d = tf.square(c)

e = tf.exp(c)

print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[-2.3635287  0.6253386]
 [-1.4655626  0.8941015]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.9582005  -0.14607397]
 [-0.56347567  0.85606223]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1.4053283   0.47926465]
 [-2.0290382   1.7501638 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.9749476 0.2296946]
 [4.116996  3.0630734]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.24528652 1.6148864 ]
 [0.1314619  5.755545  ]], shape=(2, 2), dtype=float32)


#### ___Element-Wise Primitive Tensor Operations___

In [32]:
tensor*tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[100., 121., 144.],
        [169., 196., 225.]],

       [[256., 289., 324.],
        [361., 400., 441.]]], dtype=float32)>

#### ___Transpose Matrix Multiplication___

In [34]:
matrix_u = tf.constant([[6,7,6]])
matrix_v = tf.constant([[3,4,3]])

tf.matmul(matrix_u, tf.transpose(a=matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[64]], dtype=int32)>

#### ___Squared Difference of Tensors___

In [37]:
varx = [4,5,6,1,2]
vary = 8

varz = tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  9,  4, 49, 36], dtype=int32)>

#### ___Calculate the Mean: tf.reduce_mean()___

_Similar to np.mean, except that it infers the return datatype from the input tensor, whereas np.mean allows you to specify the output type_

`tf.reduce_mean(input_tensor, axis=None, keepdims=None, name=None)`

In [38]:
# Defining a constant
numbers = tf.constant([[8., 9.], [1., 2.]])

##### ___Mean across All Axes___

In [39]:
tf.reduce_mean(input_tensor = numbers) #default axis = None

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

##### ___Mean across Columns (Reduce Rows)___

In [40]:
tf.reduce_mean(input_tensor = numbers, axis = 0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5.5], dtype=float32)>

##### ___When keepdims = True___

In [41]:
tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True) #the reduced axis is retained with a length of 1

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[4.5, 5.5]], dtype=float32)>

##### ___Mean across Rows (Reduce Columns)___

In [42]:
tf.reduce_mean(input_tensor = numbers, axis = 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([8.5, 1.5], dtype=float32)>

##### ___When keepdims= True___

In [43]:
tf.reduce_mean(input_tensor=numbers, axis=1, keepdims=True) #the reduced axis is retained with a length of 1

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[8.5],
       [1.5]], dtype=float32)>

####  ___Random Values Generation___

#### ___tf.random.normal()___
   
`tf.random.normal(shape, mean = 0, stddev =2, dtype=tf.float32, seed=None, name=None)`

In [44]:
tf.random.normal(shape = (3,2), mean=10, stddev=2, dtype=tf.float32, seed=None, name=None)

randon_num = tf.random.normal(shape = (3,2), mean=10.0, stddev=2.0)
print(randon_num)

tf.Tensor(
[[10.656339 11.083926]
 [ 6.943039  7.434379]
 [14.889196  9.439659]], shape=(3, 2), dtype=float32)


#### ___tf.random.uniform()___

`tf.random.uniform(shape, minval = 0, maxval= None, dtype=tf.float32, seed=None, name=None)`

In [45]:
tf.random.uniform(shape = (2,4), minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.5430684 , 0.05683887, 0.3740009 , 0.24902499],
       [0.34438705, 0.8166057 , 0.0044353 , 0.48354948]], dtype=float32)>

#### ___Setting the seed___

In [46]:
tf.random.set_seed(11)
random_num1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
random_num2 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
print(random_num1) #Call 1
print(random_num2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [47]:
tf.random.set_seed(11) #same seed
random_num1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
random_num2 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
print(random_num1) #Call 2
print(random_num2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


#### ___Concatenation___

In [ ]:
dice11 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
dice12 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))

# lets ADD
dice_sum1 = dice11 + dice12
# We've got three separate 10x1 matrices. To produce a single 10x3 matrix, we'll concatenate them along dimension 1.
finale_matrix = tf.concat(values=[dice11, dice12, dice_sum1], axis=1)
print(finale_matrix)

tf.Tensor(
[[ 5  5 10]
 [ 4  3  7]
 [ 5  3  8]
 [ 3  3  6]
 [ 1  4  5]
 [ 4  1  5]
 [ 5  1  6]
 [ 6  4 10]
 [ 3  3  6]
 [ 2  3  5]], shape=(10, 3), dtype=int32)


#### ___Finding the Indices of the Largest and Smallest element___

>The following functions are available:
    
>`tf.argmax(input, axis=None, name=None, output_type=tf.int64 )`

>`tf.argmin(input, axis=None, name=None, output_type=tf.int64 )`

In [48]:
# 1-D tensor
tensor_1d = tf.constant([12, 11, 51, 42, 6, 16, -8, -19, 31])
print(tensor_1d)


i = tf.argmax(input=tensor_1d)
print('index of max; ', i)
print('Max element: ',tensor_1d[i].numpy())


i = tf.argmin(input=tensor_1d,axis=0).numpy()
print('index of min: ', i)
print('Min element: ',tensor_1d[i].numpy())

tf.Tensor([ 12  11  51  42   6  16  -8 -19  31], shape=(9,), dtype=int32)
index of max;  tf.Tensor(2, shape=(), dtype=int64)
Max element:  51
index of min:  7
Min element:  -19


### ___Checkpoint___

In [ ]:
variable1 = tf.Variable([[5,6,9,3],[14,15,16,18]])
checkpoint= tf.train.Checkpoint(var=variable1)
savepath = checkpoint.save('./vars')
variable1.assign([[0,0,0,0],[0,0,0,0]])
variable1
checkpoint.restore(savepath)
print(variable1)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 5,  6,  9,  3],
       [14, 15, 16, 18]])>


#### ___Creating Functions___

___tf.function___ _is a function that will take a Python function and return a TensorFlow graph. The advantage of this is that graphs can apply optimizations and exploit parallelism in the Python function (func). tf.function is new to TensorFlow 2._


`tf.function(func=None,input_signature=None,autograph=True,experimental_autograph_options=None)`


In [49]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 3, 6) + y**3)

func = tf.function(f1)

x = tf.constant([3., -4.])
y = tf.constant([1., 4.])

# f1 and f2 return the same value, but f2 executes as a TensorFlow graph
assert f1(x,y).numpy() == func(x,y).numpy()

#The assert passes, so there is no output

# The tf. Assert() function takes a condition, and if the condition is false, it then prints the lists of given tensors and throws tf.

### ___Calculate the Gradient___

#### ___GradientTape___

_Another difference from numpy is that it can automatically track the gradient of any variable._

_Open one __GradientTape__ and `tape.watch()` track variables through._

In [50]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))

with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[0.57269156 0.9751479 ]
 [0.53572375 0.8537005 ]], shape=(2, 2), dtype=float32)


_For all variables, the calculation is tracked by default and used to find the gradient, so do not `usetape.watch()`_

In [51]:
a = tf.Variable(a)

with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[0.57269156 0.9751479 ]
 [0.53572375 0.8537005 ]], shape=(2, 2), dtype=float32)


_You can GradientTapefind higher-order derivatives by opening a few more:_

In [52]:
# double derivative
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a)+tf.square(b))
        dc_da = tape.gradient(c,a)
    d2c_d2a = outer_tape.gradient(dc_da,a)
    print(d2c_d2a)

tf.Tensor(
[[0.47573683 0.04185158]
 [1.0060201  0.24222922]], shape=(2, 2), dtype=float32)
