# ___Keras, a High-Level API for TensorFlow 2___

## ___What is Keras?___
_KERAS is an Open Source Neural Network library written in Python that runs on top of Theano or Tensorflow. It is designed to be modular, fast and easy to use. It was developed by François Chollet, a Google engineer._

_Keras doesn't handle low-level computation. Instead, it uses another library to do it, called the "Backend. So Keras is high-level API wrapper for the low-level API, capable of running on top of TensorFlow, CNTK, or Theano._

_Keras High-Level API handles the way we make models, defining layers, or set up multiple input-output models. In this level, Keras also compiles our model with loss and optimizer functions, training process with fit function. Keras doesn't handle Low-Level API such as making the computational graph, making tensors or other variables because it has been handled by the "backend" engine._

## ___What is a Backend?___
_Backend is a term in Keras that performs all low-level computation such as tensor products, convolutions and many other things with the help of other libraries such as Tensorflow or Theano. So, the "backend engine" will perform the computation and development of the models. Tensorflow is the default "backend engine" but we can change it in the configuration._

_If we want to change the backend in Keras edit our __$HOME/.Keras /Keras.json__ file and specify the different backend name such as Theano or CNTK._

```{ 
   "image_data_format": "channels_last", 
   "epsilon": 1e-07, "floatx": "float32", "backend": "tensorflow" 
}```

_Here,_

* ___image_data_format___ _represent the data format._

* ___epsilon___ _represents numeric constant. It is used to avoid DivideByZero error._

* ___floatx___ _represent the default data type float32. You can also change it to float16 or float64 using set_floatx() method._

* ___image_data_format___ _represent the data format._

## ___Advantages of Keras___

* _Fast Deployment and Easy to understand_
* _Large Community Support_
* _Have multiple Backends: You can choose Tensorflow, CNTK, and Theano as your backend with Keras. You can choose a different backend for different projects depending on your needs. Each backend has its own unique advantage._ 
* _Cross-Platform and Easy Model Deployment_
* _Multi GPUs Support_

## ___Disadvantages of Keras___

* _Cannot handle low-level API_

## ___Install Keras___
_After we install Tensorflow, let's start installing keras. Type this command in the terminal._

`pip install keras`

_But with the latest version of Tensorflow, keras comes pre installed._

## ___Architecture of Keras___

_Keras API can be divided into three main categories:_

* ___Model___
* ___Layer___
* ___Core Modules___

<img src='https://www.tutorialspoint.com/keras/images/architecture_of_keras.jpg'/>

## ___Keras Models APIs___

_There are three ways to create Keras models:_

* _The __Sequential model__, which is very straightforward (a simple list of layers), but is limited to single-input, single-output stacks of layers (as the name gives away) : The sequential API allows the user to create models layer-by-layer for most of the problems by using the strategy of sequential model. It does not allow the user to create models that can share the layers or have multiple inputs or outputs._

* _The __Functional API__, which is an easy-to-use, fully-featured API that supports arbitrary model architectures. For most people and most use cases, this is what you should be using. This is the Keras "industry strength" model. : In the functional model, the functional API allows the user to create the models. These models have a lot of flexibility as the user can easily define the models where layers are connected to just the previous and next layers. User can connect the layers to any other layer in the functional model._

* ___Model subclassing___ _, where you implement everything from scratch on your own. Use this if you have complex, out-of-the-box research use cases._

## ___Keras Layers___
_Each Keras layer in the Keras model represent the corresponding layer (input layer, hidden layer and output layer) in the actual proposed neural network model. Keras provides a lot of pre-build layers so that any complex neural network can be easily created. Some of the important Keras layers are specified below,_

* ___Core Layers___
* ___Convolution Layers___
* ___Pooling Layers___
* ___Recurrent Layers___

## ___Core Modules___
_Keras also provides a lot of built-in neural network related functions to properly create the Keras model and Keras layers. Some of the function are as follows:_

* ___Activations Module___ _− Activation function is an important concept in ANN and activation modules provides many activation function like softmax, relu, etc._

* ___Loss Module___ _− Loss module provides loss functions like mean_squared_error, mean_absolute_error, poisson, etc._

* ___Optimizer Module___ _− Optimizer module provides optimizer function like adam, sgd, etc._

* ___Regularizers___ _− Regularizer module provides functions like L1 regularizer, L2 regularizer, etc._

## ___Keras - Modules___

_Keras modules contains pre-defined classes, functions and variables which are useful for deep learning algorithm._

* ___Initializers___ - _Provides a list of initializers function._

* ___Regularizers___ - _Provides a list of regularizers function._ 
 
* ___Constraints___ - _Provides a list of constraints function._
 
* ___Activations___ - _Provides a list of activator function._ 

* ___Losses___ - _Provides a list of loss function._ 

* ___Metrics___ - _Provides a list of metrics function._ 

* ___Optimizers___ - _Provides a list of optimizer function._

* ___Callback___ - _Provides a list of callback function. We can use it during the training process to print the intermediate data as well as to stop the training itself (EarlyStopping method) based on some condition._

* ___Text processing___ - _Provides functions to convert text into NumPy array suitable for machine learning. We can use it in data preparation phase of machine learning._

* ___Image processing___ - _Provides functions to convert images into NumPy array suitable for machine learning. We can use it in data preparation phase of machine learning._

* ___Sequence processing___ - _Provides functions to generate time based data from the given input data. We can use it in data preparation phase of machine learning._

* ___Backend___ - _Provides function of the backend library like TensorFlow and Theano._

* ___Utilities___ - _Provides lot of utility function useful in deep learning._

## ___Concept of Layers___

_Keras layers are the primary building block of Keras models. Each layer receives input information, do some computation and finally output the transformed information. The output of one layer will flow into the next layer as its input._

_A Keras layer requires shape of the input (input_shape) to understand the structure of the input data, initializer to set the weight for each input and finally activators to transform the output to make it non-linear. In between, constraints restricts and specify the range in which the weight of input data to be generated and regularizer will try to optimize the layer (and the model) by dynamically applying the penalties on the weights during optimization process._

_To summarise, Keras layer requires below minimum details to create a complete layer:_

* ___Shape of the Input Data___
* ___Number of Neurons/Units in the Layer___
* ___Initializers___
* ___Regularizers___
* ___Constraints___
* ___Activations___

### ___Types of Layers___

* ___Dense Layer___

  _Dense layer is the regular deeply connected neural network layer._

  _The argument supported by Dense layer is as follows:_

  * ___units___ _represent the number of units and it affects the output layer._
  * ___activation___ _represents the activation function._
  * ___use_bias___ _represents whether the layer uses a bias vector._
  * ___kernel_initializer___ _represents the initializer to be used for kernel._
  * ___bias_initializer___ _represents the initializer to be used for the bias vector._
  * ___kernel_regularizer___ _represents the regularizer function to be applied to the kernel weights matrix._
  * ___bias_regularizer___ _represents the regularizer function to be applied to the bias vector._
  * ___activity_regularizer___ _represents the regularizer function tp be applied to the output of the layer._
  * ___kernel_constraint___ _represent constraint function to be applied to the kernel weights matrix._
  * ___bias_constraint___ _represent constraint function to be applied to the bias vector._

  _As you have seen, there is no argument available to specify the_ ___input_shape___ _of the input data._ ___input_shape___ _is a special argument, which the layer will accept only if it is designed as first layer in the model._

* ___Dropout Layers___

  _Dropout is one of the important concept in the Deep learning for Active Neurons._

  _It is used to fix the over-fitting issue. Input data may have some of the unwanted data, usually called as Noise. Dropout will try to remove the noise data and thus prevent the model from over-fitting._

   ```keras.layers.Dropout(rate, noise_shape = None, seed = None)```

  * ___rate___ _− represent the fraction of the input unit to be dropped. It will be from 0 to 1._
  * ___noise_shape___ _represent the dimension of the shape in which the dropout to be applied. For example, the input shape is (batch_size, timesteps, features). Then, to apply dropout in the timesteps, (batch_size, 1, features) need to be specified as noise_shape._
  * ___seed___ _− random seed._

* ___Flatten Layers___

  _Flatten is used to flatten the input. For example, if flatten is applied to layer having input shape as (batch_size, 2,2), then the output shape of the layer will be (batch_size, 4)_

  ```keras.layers.Flatten(data_format = None)```
  * ___data_format___ _is an optional argument and it is used to preserve weight ordering when switching from one data format to another data format. It accepts either ___channels_last___ or ___channels_first___ as value. channels_last is the default one and it identifies the input shape as (batch_size, ..., channels) whereas channels_first identifies the input shape as (batch_size, channels, ...)_

* ___Reshape Layers___

  _Reshape is used to change the shape of the input._

* ___Permute Layers___

  _Permute is also used to change the shape of the input using pattern._

* ___RepeatVector Layers___

  _RepeatVector is used to repeat the input for set number, n of times._

* ___Lambda Layers___

  _Lambda is used to transform the input data using an expression or function._

* ___Convolution Layers___

  _Keras contains a lot of layers for creating Convolution based ANN, popularly called as Convolution Neural Network (CNN)._

* ___Pooling Layer___

  _It is used to perform max pooling operations on temporal data._

* ___Locally connected Layer___

  _Locally connected layers are similar to Conv1D layer but the difference is Conv1D layer weights are shared but here weights are unshared._

* ___Merge Layer___

  _It is used to merge a list of inputs._

* ___Embedding Layer___

  _It performs embedding operations in input layer. It is used to convert positive into dense vectors of fixed size. Its main application is in text analysis._

### ___Input Shape___
_In deep learning, all type of input data like text, images or videos will be first converted into array of numbers and then feed into the algorithm. Input numbers may be single dimensional array, two dimensional array (matrix) or multi-dimensional array. We can specify the dimensional information using shape, a tuple of integers. To create the first layer of the model (or input layer of the model), shape of the input data should be specified._

### ___Initializers___
_Initializers module provides different functions to set these initial weight. Some of the Keras Initializer function are as follows:_

`from keras import initializers`

* ___Zeros___

```Dense(512, activation = 'relu', input_shape = (784,), kernel_initializer = initializers.Zeros())```

* ___Ones___

```Dense(512, activation = 'relu', input_shape = (784,), kernel_initializer = initializers.Ones())```

* ___Constant___

```Dense(512, activation = 'relu', input_shape = (784,), kernel_initializer = initializers.Constant(value = 0))```

* ___RandomNormal___

```Dense(512, activation = 'relu', input_shape = (784,), kernel_initializer = initializers..RandomNormal(mean=0.0, stddev = 0.05, seed = None))```

* ___RandomUniform___

```Dense(512, activation = 'relu', input_shape = (784,), kernel_initializer = RandomUniform(minval = -0.05, maxval = 0.05, seed = None))```

* ___TruncatedNormal___

```Dense(512, activation = 'relu', input_shape = (784,), kernel_initializer = TruncatedNormal(mean = 0.0, stddev = 0.05, seed = None))```

* ___GlorotNormal___

```Dense(512, activation = 'relu', input_shape = (784,), kernel_initializer = glorot_normal(seed=None))```

$stddev = sqrt(2 / (fan_in + fan_out))$

* ___GlorotUniform___

_It draws samples from a uniform distribution within -limit, limit where limit is $sqrt(6 / (fan_in + fan_out))$ where fan_in is the number of input units in the weight tensor and fan_out is the number of output units in the weight tensor._

```Dense(512, activation = 'relu', input_shape = (784,), kernel_initializer = glorot_uniform(seed = None))```

* ___he_normal___
_Generates value using he normal distribution of input data._

```Dense(512, activation = 'relu', input_shape = (784,), kernel_initializer = he_normal(seed = None))```

$stddev = sqrt(2 / fan_in)$

_works best with Relu_

* ___he_uniform___
_Generates value using he uniform distribution of input data._

```Dense(512, activation = 'relu', input_shape = (784,), kernel_initializer = he_uniform(seed = None))```

$stddev = sqrt(6 / fan_in)$

_works best with Relu_

* ___Identity___

```Dense(512, activation = 'relu', input_shape = (784,), kernel_initializer = Identity(gain = 1.0))```

* ___Orthogonal___

```Dense(512, activation = 'relu', input_shape = (784,), kernel_initializer = Orthogonal(gain = 1.0, seed = None))```

* ___VarianceScaling___

_Generates value based on the input shape and output shape of the layer along with the specified scale._

```Dense(512, activation = 'relu', input_shape = (784,), kernel_initializer = VarianceScaling(scale = 1.0, mode = 'fan_in', distribution = 'normal', seed = None))```

_where,_
  * _scale represent the scaling factor_
  * _mode represent any one of fan_in, fan_out and fan_avg values_
  * _distribution represent either of normal or uniform_

_It finds the stddev value for normal distribution using below formula and then find the weights using normal distribution,_

$stddev = sqrt(scale / n)$

_where n represent,_
  * _number of input units for mode = fan_in_
  * _number of out units for mode = fan_out_
  * _average number of input and output units for mode = fan_avg_

_Similarly, it finds the limit for uniform distribution using below formula and then find the weights using uniform distribution,_

$limit = sqrt(3 * scale / n)$

### ___Constraints___

_A constraint will be set on the parameter (weight) during optimization phase. Constraints module provides different functions to set the constraint on the layer. Some of the constraint functions are as follows:_

`from keras import constraints `

* ___NonNeg___

_Constrains weights to be non-negative._

```model.add(Dense(512, activation = 'relu', input_shape = (784,), kernel_constraint = constraints.NonNeg()))```

* ___UnitNorm___

_Constrains weights to be unit norm._

```model.add(Dense(512, activation = 'relu', input_shape = (784,), kernel_constraint = constraints.UnitNorm(axis = 0)))```

* ___MaxNorm___

_Constrains weight to norm less than or equals to the given value._

```model.add(Dense(512, activation = 'relu', input_shape = (784,), kernel_constraint = constraints.MaxNorm(max_value = 2, axis = 0)))```

  * _max_value represent the upper bound_
  * _axis represent the dimension in which the constraint to be applied. e.g. in Shape (2,3,4) axis 0 denotes first dimension, 1 denotes second dimension and 2 denotes third dimension_

* ___MinMaxNorm___

_Constrains weights to be norm between specified minimum and maximum values._

```model.add(Dense(512, activation = 'relu', input_shape = (784,), kernel_constraint = constraints.MinMaxNorm(min_value = 0.0, max_value = 1.0, rate = 1.0, axis = 0)))```

  * _where, rate represent the rate at which the weight constrain is applied._

### ___Regularizers___
_Regularizers are used in the optimization phase. It applies some penalties on the layer parameter during optimization. Keras regularization module provides below functions to set penalties on the layer. Regularization applies per-layer basis only._

* ___L1 Regularizer___
_It provides L1 based regularization._

```model.add(Dense(512, activation = 'relu', input_shape = (784,), kernel_regularizer=regularizers.l1(l1=0.01)))```

* ___L2 Regularizer___
_It provides L2 based regularization._

```model.add(Dense(512, activation = 'relu', input_shape = (784,), kernel_regularizer=regularizers.l2(l2=0.01)))```

* ___L1 and L2 Regularizer___
_It provides both L1 and L2 based regularization._

```model.add(Dense(512, activation = 'relu', input_shape = (784,), kernel_regularizer=regularizers.l1_l2(l1=1e-5, l2=1e-4)))```

### ___Activations___

_The Activation function does a nonlinear transformation of the input data and thus enable the neurons to learn better. Output of a neuron depends on the activation function._

```from keras.layers import Activation```

```model.add(Dense(512, activation = 'exponential', input_shape = (784,)))```

___activation = exponential, relu, softmax, elu, sigmoid, tanh, softplus, linear, etc.___

## ___Concept of Models___

_Keras model represents the actual neural network model. Keras provides a two mode to create the model, simple and easy to use Sequential API as well as more flexible and advanced Functional API._

### ___Sequential Model___

_To build a Keras Sequential model, you add layers to it in the same order that you want the computations to be undertaken by the network._

_After you have built your model, you compile it; this optimizes the computations that are to be undertaken, and is where you allocate the optimizer and the loss function you want your model to use._

_The next stage is to fit the model to the data. This is commonly known as training the model, and is where all the computations take place. It is possible to present the data to the model either in batches, or all at once._

_Next, you evaluate your model to establish its accuracy, loss, and other metrics. Finally, having trained your model, you can use it to make predictions on new data. So, the workflow is: build, compile, fit, evaluate, make predictions._

```from keras.models import Sequential```

_There are two ways to create a Sequential model. Let's take a look at each of them._

#### ___Using Sequential Model___

_Firstly, you can pass a list of layer instances to the constructor, as in the following example. For now, we will just explain enough to allow you to understand what is happening here._

_Acquire the data. MNIST is a dataset of hand-drawn numerals, each on a 28 x 28 pixel grid. Every individual data point is an unsigned 8-bit integer (uint8), as are the labels:_

##### _Loading the Dataset_

In [2]:
import tensorflow as tf 

# Load Dataset from Keras inbuilt Datasets
mnist_data = tf.keras.datasets.mnist

(train_x,train_y), (test_x, test_y) = mnist_data.load_data()

11493376/11490434 [==============================] - 0s 0us/step


##### _Defining the Variables_

In [9]:
epochs = 5
batch_size = 32

___Mini-batching___

_Mini-batching is a technique for training on subsets of the dataset instead of all the data at one time. This provides the ability to train a model, even if a computer lacks the memory to store the entire dataset._

_Mini-batching is computationally inefficient, since you can't calculate the loss simultaneously across all samples. However, this is a small price to pay in order to be able to run the model at all._

_It's also quite useful combined with SGD. The idea is to randomly shuffle the data at the start of each epoch, then create the mini-batches. For each mini-batch, you train the network weights with gradient descent. Since these batches are random, you're performing SGD with each batch._

___Epochs___

_An epoch is a single forward and backward pass of the whole dataset. This is used to increase the accuracy of the model without requiring more data._



In [4]:
# normalize all the data points and cast the labels to int64

train_x, test_x = tf.cast(train_x/255.0, tf.float32), tf.cast(test_x/255.0, tf.float32)
train_y, test_y = tf.cast(train_y,tf.int64),tf.cast(test_y,tf.int64)

#### ___Sequential Model 1___

##### _Building the Architecture_

In [5]:
# Sequential Model 1

mnistmodel1 = tf.keras.models.Sequential([
tf.keras.layers.Flatten(),
tf.keras.layers.Dense(512,activation=tf.nn.relu),
tf.keras.layers.Dropout(0.2),
tf.keras.layers.Dense(10,activation=tf.nn.softmax)
])

##### _Compiling the Model_

In [6]:
# choosing Optimizer for backpropogation
optimiser = tf.keras.optimizers.Adam()

# Compiling model with loss function , optimizer and metrics
mnistmodel1.compile(optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

___Loss___

_Loss function is used to find error or deviation in the learning process. Keras requires loss function during model compilation process._

_Keras provides quite a few loss function in the losses module and they are as follows:_

* ___mean_squared_error___
* ___mean_absolute_error___
* ___mean_absolute_percentage_error___
* ___mean_squared_logarithmic_error___
* ___squared_hinge___
* ___hinge___
* ___categorical_hinge___
* ___logcosh___
* ___huber_loss___
* ___categorical_crossentropy___
* ___sparse_categorical_crossentropy___
* ___binary_crossentropy___
* ___kullback_leibler_divergence___
* ___poisson___
* ___cosine_proximity___
* ___is_categorical_crossentropy___

___Metrics___

_Metrics is used to evaluate the performance of your model. It is similar to loss function, but not used in training process. Keras provides quite a few metrics as a module, metrics and they are as follows:_

* ___accuracy___
* ___binary_accuracy___
* ___categorical_accuracy___
* ___sparse_categorical_accuracy___
* ___top_k_categorical_accuracy___
* ___sparse_top_k_categorical_accuracy___
* ___cosine_proximity___
* ___clone_metric___

##### _Fitting the Model_

In [7]:
mnistmodel1.fit(train_x, train_y, batch_size= batch_size, epochs= epochs)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2203 - accuracy: 0.9339
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0966 - accuracy: 0.9702
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0693 - accuracy: 0.9789
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0540 - accuracy: 0.9834
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0445 - accuracy: 0.9851


##### _Evaluate the mnistmodel1_

In [8]:
mnistmodel1.evaluate(test_x, test_y)

313/313 [==============================] - 1s 2ms/step - loss: 0.0655 - accuracy: 0.9804


[0.06554202735424042, 0.980400025844574]

_This represents a loss of 0.06 and an accuracy of 0.9801 on the test data._

_An accuracy of 0.98 means that out of 100 test data points, 98 were, on average, correctly identified by the model._

In [20]:
mnistmodel1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 512)               401920    
_________________________________________________________________
dropout (Dropout)            (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


#### ___Sequential Model 2___

##### _Building the Architecture & Compiling_

In [10]:
mnistmodel2 = tf.keras.models.Sequential();

mnistmodel2.add(tf.keras.layers.Flatten())
mnistmodel2.add(tf.keras.layers.Dense(512, activation='relu'))
mnistmodel2.add(tf.keras.layers.Dropout(0.2))
mnistmodel2.add(tf.keras.layers.Dense(10,activation=tf.nn.softmax))

mnistmodel2.compile(optimizer= tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy',metrics = ['accuracy'])

##### _Fitting the mnistmodel2_

In [11]:
mnistmodel2.fit(train_x, train_y, batch_size=64, epochs=5)

Epoch 1/5
938/938 [==============================] - 5s 6ms/step - loss: 0.2462 - accuracy: 0.9285
Epoch 2/5
938/938 [==============================] - 5s 6ms/step - loss: 0.1069 - accuracy: 0.9682
Epoch 3/5
938/938 [==============================] - 5s 6ms/step - loss: 0.0730 - accuracy: 0.9781
Epoch 4/5
938/938 [==============================] - 5s 6ms/step - loss: 0.0576 - accuracy: 0.9815
Epoch 5/5
938/938 [==============================] - 5s 6ms/step - loss: 0.0436 - accuracy: 0.9868


##### _Evaluate the mnistmodel2_

In [12]:
mnistmodel2.evaluate(test_x, test_y)

313/313 [==============================] - 1s 2ms/step - loss: 0.0642 - accuracy: 0.9809


[0.06417829543352127, 0.98089998960495]

### ___Functional API___

_The functional API lets you build much more complex architectures than the simple linear stack of Sequential models we have seen previously. It also supports more advanced models. These models include multi-input and multi-output models, models with shared layers, and models with residual connections._

##### _Building the Architecture_

In [13]:
inputs = tf.keras.Input(shape=(28,28)) # Returns a 'placeholder' tensor

x = tf.keras.layers.Flatten()(inputs)
x = tf.keras.layers.Dense(512, activation='relu',name='d1')(x)
x = tf.keras.layers.Dropout(0.2)(x)

predictions = tf.keras.layers.Dense(10,activation=tf.nn.softmax, name='d2')(x)

mnistmodel3 = tf.keras.Model(inputs=inputs, outputs=predictions)

##### _Compile & Fit_

In [14]:
optimiser = tf.keras.optimizers.Adam()

mnistmodel3.compile(optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

mnistmodel3.fit(train_x, train_y, batch_size=32, epochs=epochs)

Epoch 1/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.2190 - accuracy: 0.9350
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0970 - accuracy: 0.9703
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0669 - accuracy: 0.9789
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0530 - accuracy: 0.9829
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0415 - accuracy: 0.9865


##### _Evaluate the mnistmodel3_

In [15]:
mnistmodel3.evaluate(test_x, test_y)

313/313 [==============================] - 1s 2ms/step - loss: 0.0597 - accuracy: 0.9827


[0.059650298207998276, 0.982699990272522]

### ___Subclassing the Keras Model___

##### _Building the Subclass Architecture_

In [16]:
class MNISTModel(tf.keras.Model):
    def __init__(self, num_classes=10):
        super(MNISTModel, self).__init__()
        # Define your layers here.
        inputs = tf.keras.Input(shape=(28,28)) # Returns a placeholder tensor
        self.x0 = tf.keras.layers.Flatten()
        self.x1 = tf.keras.layers.Dense(512, activation='relu',name='d1')
        self.x2 = tf.keras.layers.Dropout(0.2)
        self.predictions = tf.keras.layers.Dense(10,activation=tf.nn.softmax, name='d2')


    def call(self, inputs):
    # This is where to define your forward pass
    # using the layers previously defined in `__init__`
        x = self.x0(inputs)
        x = self.x1(x)
        x = self.x2(x)
        return self.predictions(x)

In [17]:
mnistmodel4 = MNISTModel()

##### _Compile & Fit_

In [18]:
batch_size = 32
steps_per_epoch = len(train_x.numpy())//batch_size
print(steps_per_epoch)

mnistmodel4.compile (optimizer= tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy',metrics = ['accuracy'])

mnistmodel4.fit(train_x, train_y, batch_size=batch_size, epochs=epochs)

1875
Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2212 - accuracy: 0.9346
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0963 - accuracy: 0.9698
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0702 - accuracy: 0.9779
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0539 - accuracy: 0.9828
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0438 - accuracy: 0.9864


##### _Evaluate the mnistmodel4_

In [19]:
mnistmodel4.evaluate(test_x, test_y)

313/313 [==============================] - 1s 2ms/step - loss: 0.0649 - accuracy: 0.9812


[0.0648932158946991, 0.9811999797821045]

##### ___Model Prediction___
_Prediction is the final step and our expected outcome of the model generation. Keras provides a method, predict to get the prediction of the trained model. The signature of the predict method is as follows,_

`predict(
   x, 
   batch_size = None, 
   verbose = 0, 
   steps = None, 
   callbacks = None, 
   max_queue_size = 10, 
   workers = 1, 
   use_multiprocessing = False
)`

_Here, all arguments are optional except the first argument, which refers the unknown input data. The shape should be maintained to get the proper prediction._

### ___Saving and Loading Keras Models___

_The Keras API in TensorFlow has the ability to save and restore models easily. This is done as follows, and saves the model in the current directory. Of course, a longer path may be passed here:_

#### ___Saving a model___
    
`model.save('./model_name.h5')`

_This will save the model architecture, its weights, its training state (loss, optimizer), and the state of the optimizer, so that you can carry on training the model from where you left off._


_Loading a saved model is done as follows. Note that if you have compiled your model, the load will compile your model using the saved training configuration:_

#### ___Loading a model___

`from tensorflow.keras.models import load_model`

`new_model = load_model('./model_name.h5')`

_It is also possible to save just the architecture of the model._

#### ___Saving the Model Architecture___

`json_string = model.to_json()`

_To Load the saved Architecture_

#### ___Load Model Architecture___

`from tensorflow.keras.models import model_from_json`

`model_architecture = model_from_json(json_string)`

_It is also possible to save just the model weights and load them with this (in which case, you must build your architecture to load the weights into):_

#### ___Saving the Model Weights___
    
`model.save_weights('./model_weights.h5')`
    
_Then use the following to load it:_

#### ___Loding the Weights___
    
`model.load_weights('./model_weights.h5')`

### ___One-Hot Encoding___

_One-hot encoding (OHE) is where a tensor is constructed from the data labels with a 1 in each of the elements corresponding to a label's value, and 0 everywhere else; that is, one of the bits in the tensor is hot (1)._

#### ___One-Hot Encoding 1___

_In this example, we are converting a decimal value of 7 to a one-hot encoded value of 0000000100 using_

`tf.one_hot()`

In [57]:
z = 7

z_train_ohe = tf.one_hot(z, depth=10).numpy()

print(z, "is ",z_train_ohe,"when one-hot encoded with a depth of 10")

7 is  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] when one-hot encoded with a depth of 10


#### ___One-Hot Encoding 2___

_Using the fashion MNIST dataset._

_The original labels are integers from 0 to 9, so, for example, a label of 5 becomes 0000010000 when onehot encoded, but note the difference between the index and the label stored at that index:_

In [59]:
from tensorflow.keras.datasets import fashion_mnist

width, height, = 28,28

# total classes
n_classes = 10

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [60]:
split = 50000
(y_train, y_valid) = y_train[:split], y_train[split:]

In [61]:
y_train_ohe = tf.one_hot(y_train, depth=n_classes).numpy()
y_valid_ohe = tf.one_hot(y_valid, depth=n_classes).numpy()
y_test_ohe = tf.one_hot(y_test, depth=n_classes).numpy()

# show difference between the original label and a one-hot-encoded label
i=8
print(y_train[i]) # 'ordinary' number value of label at index i=8 is 5

# note the difference between the index of 8 and the label at that index which is 5
print(y_train_ohe[i]) 

5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


## ___Keras Datasets Module___

_Before creating a model, we need to choose a problem, need to collect the required data and convert the data to NumPy array. Once data is collected, we can prepare the model and train it by using the collected data. Data collection is one of the most difficult phase of machine learning. Keras provides a special module, datasets to download the online machine learning data for training purposes. It fetches the data from online server, process the data and return the data as training and test set._

_The data available in the module are as follows:_

  * ___CIFAR10 small image classification___
  * ___CIFAR100 small image classification___
  * ___IMDB Movie reviews sentiment classification___
  * ___Reuters newswire topics classification___
  * ___MNIST database of handwritten digits___
  * ___Fashion-MNIST database of fashion articles___
  * ___Boston housing price regression dataset___

_They are all accessed with the function:_

`load_data()`  

_For example, to load the fashion_mnist dataset, use the following:_

`(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()`

## ___Options to Load Data into TensorFlow___
_The first step before training a machine learning algorithm is to load the data. There is two commons way to load data:_

1. ___Load data into memory___ _: It is the simplest method. You load all your data into memory as a single array. You can write a Python code. This lines of code are unrelated to Tensorflow._

2. ___Tensorflow Data Pipeline___ _: Tensorflow has built-in API that helps you to load the data, perform the operation and feed the machine learning algorithm easily. This method works very well especially when you have a large dataset. For instance, image records are known to be enormous and do not fit into memory. The data pipeline manages the memory by itself._

### ___Load Data in Memory___

_If your dataset is not too big, i.e., less than 10 gigabytes, you can use the first method. The data can fit into the memory. You can use a famous library called Pandas to import CSV files._

### ___Load Data with Tensorflow Pipeline___

_The second method works best if you have a large dataset. For instance, if you have a dataset of 50 gigabytes, and your computer has only 16 gigabytes of memory then the machine will crash._

_In this situation, you need to build a Tensorflow pipeline. The pipeline will load the data in __batch__, or small chunk. Each batch will be pushed to the pipeline and be ready for the training. Building a pipeline is an excellent solution because it allows you to use parallel computing. It means Tensorflow will train the model across multiple CPUs. It fosters the computation and permits for training powerful neural network._

#### ___How to create Datasets?___
_Tensorflow provides various methods to create Datasets from numpy arrays, text files, CSV files, tensors, etc. Let’s look at few methods below:_

#### ___from_tensor_slices___ 

_It accepts single or multiple numpy arrays or tensors. Dataset created using this method will emit only one data at a time._

In [10]:
import numpy as np
import tensorflow as tf

# source data - numpy array
data = np.arange(10)

# create a dataset from numpy array
dataset = tf.data.Dataset.from_tensor_slices(data)
dataset

<TensorSliceDataset shapes: (), types: tf.int64>

In [11]:
for elem in dataset:
  print(elem.numpy())

0
1
2
3
4
5
6
7
8
9


In [12]:
it = iter(dataset)
print(next(it).numpy())

0


In [15]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4, 10]))
dataset1

<TensorSliceDataset shapes: (10,), types: tf.float32>

In [21]:
iterator = tf.compat.v1.data.make_one_shot_iterator(dataset1)

for item in dataset1:
    number = iterator.get_next().numpy()
    print(number)

[0.41135347 0.03141069 0.54174507 0.28996527 0.51327515 0.25448108
 0.30541623 0.12145805 0.87665796 0.4771775 ]
[0.9282093  0.92357934 0.71846044 0.03223097 0.94496965 0.7557212
 0.49731612 0.16906571 0.33520496 0.0521158 ]
[0.92983496 0.04271567 0.3680334  0.51463735 0.6034411  0.9591875
 0.30914724 0.61624277 0.74324155 0.6654117 ]
[0.7436255  0.23171341 0.9662912  0.85830724 0.37194717 0.13710117
 0.6405338  0.2892282  0.13706768 0.06933939]


In [17]:
dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))

dataset2.element_spec

(TensorSpec(shape=(), dtype=tf.float32, name=None),
 TensorSpec(shape=(100,), dtype=tf.int32, name=None))

#### ___from_tensors___ 

_It also accepts single or multiple numpy arrays or tensors. Dataset created using this method will emit all the data at once._

In [18]:
data = tf.constant(10)

dataset = tf.data.Dataset.from_tensors(data)
dataset

<TensorDataset shapes: (), types: tf.int32>

In [53]:
# Dataset containing a sparse tensor.
dataset4 = tf.data.Dataset.from_tensors(tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4]))
dataset4

<TensorDataset shapes: (3, 4), types: tf.int32>

In [56]:
iterator = tf.compat.v1.data.make_one_shot_iterator(dataset4)

for item in dataset4:
    number = iterator.get_next().values.numpy()
    print(number)

[1 2]


#### ___from_generator___ 

_Creates a Dataset whose elements are generated by a function._

In [19]:
def generator():
  for i in range(10):
    yield 2*i
    
dataset = tf.data.Dataset.from_generator(generator, (tf.int32))
dataset

<FlatMapDataset shapes: <unknown>, types: tf.int32>

#### ___Operations___

___Operations to apply to the data, these include operations such as:___

* ___batch()___ _– this allows you to consume the data from your TensorFlow Dataset in batches_
* ___map()___ _– this allows you to transform the data using lambda statements applied to each element_
* ___zip()___ _– this allows you to zip together different Dataset objects into a new Dataset, in a similar way to the Python zip function_
* ___filter()___ _– this allows you to remove problematic data-points in your data-set, again based on some lambda function_
* ___repeat()___ _– this operation restricts the number of times data is consumed from the Dataset before a tf.errors.OutOfRangeError error is thrown means that the dataset will be re-fed from the beginning when its end is reached (continuously)_
* ___shuffle()___ _– this operation shuffles the data in the Dataset_

_[Reference](https://www.kaggle.com/jalammar/intro-to-data-input-pipelines-with-tf-data)_

In [22]:
## BATCH

number_items = 11
number_list1 = np.arange(number_items)

number_list1_dataset = tf.data.Dataset.from_tensor_slices(number_list1).batch(3, drop_remainder = False)

iterator = tf.compat.v1.data.make_one_shot_iterator(number_list1_dataset)

for item in number_list1_dataset:
    number = iterator.get_next().numpy()
    print(number)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10]


In [ ]:
## ZIP

data_set1 = [1,2,3,4,5]
data_set2 = ['a','e','i','o','u']
data_set1 = tf.data.Dataset.from_tensor_slices(data_set1)
data_set2 = tf.data.Dataset.from_tensor_slices(data_set2)

zipped_datasets = tf.data.Dataset.zip((data_set1, data_set2))

iterator = tf.compat.v1.data.make_one_shot_iterator(zipped_datasets)

for item in zipped_datasets:
    number = iterator.get_next()
    print(number)

In [ ]:
## CONCAT

datas1 = tf.data.Dataset.from_tensor_slices([1,2,3,5,7,11,13,17])
datas2 = tf.data.Dataset.from_tensor_slices([19,23,29,31,37,41])

datas3 = datas1.concatenate(datas2)

print(datas3)

iterator = tf.compat.v1.data.make_one_shot_iterator(datas3)

for i in range(14):
    number = iterator.get_next()
    print(number)

#### ___ImageDataGenerator___

In [20]:
flowers = tf.keras.utils.get_file(
    'flower_photos',
    'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
    untar=True)

img_gen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255, rotation_range=20)

images, labels = next(img_gen.flow_from_directory(flowers))

print(images.dtype, images.shape)
print(labels.dtype, labels.shape)

228818944/228813984 [==============================] - 2s 0us/step
Found 3670 images belonging to 5 classes.
float32 (32, 256, 256, 3)
float32 (32, 5)


#### ___TFRecord___

_TFRecord format is a binary file format. For large files, it is a good choice because binary files take up less disc space, take less time to copy, and can be read very efficiently from the disc. All this can have a significant effect on the efficiency of your data pipeline and thus, the training time of your model. The format is also optimized in a
variety of ways for use with TensorFlow. It is a little complex because data has to be converted into
the binary format prior to storage and decoded when read back._

_A TFRecord file is a sequence of binary strings, its structure must be specified prior to saving so that it can be properly written and subsequently read back._

_TensorFlow has two structures for this,_

`tf.train.Example`

`tf.train.SequenceExample. `

_We have to store each sample of your data in one of these structures, then serialize it, and use_ `tf.python_io.TFRecordWriter` _to save it to disk._

_A feature is a dictionary containing the data that is passed to tf.train.Example prior to serialization and saving the data._

##### ___TF Record 1___

In [23]:
# WRITE TFRECORD
data = np.array([10.,11.,12.,13.,14.,15.])

def npy_to_tfrecords(fname,data):
    writer = tf.io.TFRecordWriter(fname)

    feature={}
    feature['data'] = tf.train.Feature(float_list=tf.train.FloatList(value=data))
    
    example = tf.train.Example(features=tf.train.Features(feature=feature))
    
    serialized = example.SerializeToString()
    
    writer.write(serialized)
    
    writer.close()

npy_to_tfrecords("./myfile.tfrecords",data)

_The code to read the record back is as follows._

_A_ ___parse_function___ _function is constructed that decodes the dataset read back from the file. This requires a dictionary_ _(keys_to_features)_ _with the same name and structure as the saved data:_

In [24]:
data_set = tf.data.TFRecordDataset("./myfile.tfrecords")

def parse_function(example_proto):
    keys_to_features = {'data':tf.io.FixedLenSequenceFeature([], dtype = tf.float32, allow_missing = True) }

    parsed_features = tf.io.parse_single_example(serialized=example_proto, features=keys_to_features)

    return parsed_features['data']

data_set = data_set.map(parse_function)

iterator = tf.compat.v1.data.make_one_shot_iterator(data_set)

# array is retrieved as one item
item = iterator.get_next()
print(item)

print(item.numpy())

print(item[2].numpy())

tf.Tensor([10. 11. 12. 13. 14. 15.], shape=(6,), dtype=float32)
[10. 11. 12. 13. 14. 15.]
12.0


##### ___TF Record  2___

In [25]:
filename = './students.tfrecords'

dataset = {
'ID': 61553,
'Name': ['Jones', 'Felicity'],
'Scores': [45.6, 97.2]}

_Using this, we can construct a tf.train.Example class, again using the `Feature()` method. Note how we have to encode our string:_


In [26]:
ID = tf.train.Feature(int64_list=tf.train.Int64List(value=[dataset['ID']]))
Name = tf.train.Feature(bytes_list=tf.train.BytesList(value=[n.encode('utf-8') for n in dataset['Name']]))
Scores = tf.train.Feature(float_list=tf.train.FloatList(value=dataset['Scores']))

example = tf.train.Example(features=tf.train.Features(feature={'ID': ID, 'Name': Name, 'Scores': Scores }))

In [27]:
writer_rec = tf.io.TFRecordWriter(filename)

writer_rec.write(example.SerializeToString())

writer_rec.close()

In [28]:
data_set = tf.data.TFRecordDataset("./students.tfrecords")

def parse_function(example_proto):
    keys_to_features = {'ID':tf.io.FixedLenFeature([], dtype = tf.int64),
                        'Name':tf.io.VarLenFeature(dtype = tf.string),
                        'Scores':tf.io.VarLenFeature(dtype = tf.float32)}

    parsed_features = tf.io.parse_single_example(serialized=example_proto, features=keys_to_features)

    return parsed_features["ID"], parsed_features["Name"],parsed_features["Scores"]

In [29]:
dataset = data_set.map(parse_function)

iterator = tf.compat.v1.data.make_one_shot_iterator(dataset)
items = iterator.get_next()

In [43]:
print(items)

(<tf.Tensor: shape=(), dtype=int64, numpy=61553>, <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7f9f902eda20>, <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7f9f902ed748>)


_Now we can extract our data from item (note that the string must be decoded (from bytes) where the default for our Python 3 is utf8). Note also that the string and the array of floats are returned as sparse arrays, and to extract them from the record, we use the sparse array value method:_

In [51]:
print("ID: ",items[0].numpy())

name = items[1].values.numpy()
print(name)
name1 = name[0].decode()
name2 = name[1].decode('utf8')

print("Name:", name1,",",name2)

print("Scores: ",item[2].numpy())

ID:  61553
[b'Jones' b'Felicity']
Name: Jones , Felicity
Scores:  12.0


#### ___Comma-Separated Values (CSV)___

_CSV files are a very popular method of storing data. TensorFlow 2 contains flexible methods for dealing with them._

`tf.data.experimental.CsvDataset`

##### ___CSV 1___

_With the following arguments, our dataset will consist of two items taken from each row of the filename file, both of the float type, with the first line of the file ignored and columns 1 and 2 used (column numbering is, of course, 0-based):_


In [ ]:
filename = ["./size_1000.csv"]
record_defaults = [tf.float32] * 2 # two required float columns

data_set = tf.data.experimental.CsvDataset(filename, record_defaults, header=True, select_cols=[1,2])

for item in data_set:
    print(item)

##### ___CSV 2___

_In this example, and with the following arguments, our dataset will consist of one required float, one optional float with a default value of 0.0, and an int, where there is no header in the CSV file and only columns 1, 2, and 3 are imported:_

In [ ]:
filename = "mycsvfile.txt"
record_defaults = [tf.float32, tf.constant([0.0], dtype=tf.float32), tf.int32,]

data_set = tf.data.experimental.CsvDataset(filename, record_defaults, header=False, select_cols=[1,2,3])

for item in data_set:
    print(item)

(<tf.Tensor: shape=(), dtype=float32, numpy=428000.0>, <tf.Tensor: shape=(), dtype=float32, numpy=555.0>, <tf.Tensor: shape=(), dtype=int32, numpy=42>)
(<tf.Tensor: shape=(), dtype=float32, numpy=-5.3>, <tf.Tensor: shape=(), dtype=float32, numpy=0.0>, <tf.Tensor: shape=(), dtype=int32, numpy=69>)


##### ___CSV 3___

In [ ]:
filename = "file1.txt"
record_defaults = [tf.float32, tf.float32, tf.string ,]

dataset = tf.data.experimental.CsvDataset(filename, record_defaults, header=False)

for item in dataset:
    print(item[0].numpy(), item[1].numpy(),item[2].numpy().decode() )


12.6 23.4  Abc.co.uk
98.7 56.8  Xyz.com
34.2 68.1  Pqr.net


#### ___Dataset in Action___

In [62]:
mnist = tf.keras.datasets.mnist

(train_x,train_y), (test_x, test_y) = mnist.load_data()
train_x, test_x = train_x/255.0, test_x/255.0
epochs=10

11493376/11490434 [==============================] - 0s 0us/step


In [63]:
training_dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y)).batch(32).shuffle(10000)
training_dataset = training_dataset.map(lambda x, y: (tf.image.random_flip_left_right(x), y))
training_dataset = training_dataset.repeat()

In [64]:
testing_dataset = tf.data.Dataset.from_tensor_slices((test_x, test_y)).batch(32).shuffle(10000)
testing_dataset = training_dataset.repeat()

In [65]:
# Now in the fit() function, we can pass the dataset directly in, as follows:

model5 = tf.keras.models.Sequential([
 tf.keras.layers.Flatten(),
 tf.keras.layers.Dense(512,activation=tf.nn.relu),
 tf.keras.layers.Dropout(0.2),
 tf.keras.layers.Dense(10,activation=tf.nn.softmax)
])

In [67]:
steps_per_epoch = len(train_x)//32 # required becuase of the repeat() on the dataset

optimiser = tf.keras.optimizers.Adam()

model5.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

In [68]:
model5.fit(training_dataset, epochs=epochs, steps_per_epoch = steps_per_epoch)

Epoch 1/10

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

1875/1875 [==============================] - 10s 5ms/step - loss: 0.3612 - accuracy: 0.8900
Epoch 2/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1827 - accuracy: 0.9442
Epoch 3/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1400 - accuracy: 0.9568
Epoch 4/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1165 - accuracy: 0.9645
Epoch 5/10
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1000 - accuracy: 

In [69]:
model5.evaluate(testing_dataset,steps=10)

10/10 [==============================] - 0s 4ms/step - loss: 0.0187 - accuracy: 0.9937


[0.01874697580933571, 0.9937499761581421]

In [70]:
import datetime as dt

callbacks = [
  # Write TensorBoard logs to `./logs` directory
  tf.keras.callbacks.TensorBoard(log_dir='log/{}/'.format(dt.datetime.now().strftime("%Y-%m-%d-%H-%M-%S")))
]

In [71]:
model5.fit(training_dataset, epochs = epochs, steps_per_epoch = steps_per_epoch,
          validation_data = testing_dataset,
          validation_steps = 3)

Epoch 1/10
1875/1875 [==============================] - 13s 7ms/step - loss: 0.0607 - accuracy: 0.9806 - val_loss: 0.0261 - val_accuracy: 0.9896
Epoch 2/10
1875/1875 [==============================] - 12s 7ms/step - loss: 0.0575 - accuracy: 0.9817 - val_loss: 0.0467 - val_accuracy: 0.9688
Epoch 3/10
1875/1875 [==============================] - 12s 7ms/step - loss: 0.0525 - accuracy: 0.9826 - val_loss: 0.0614 - val_accuracy: 0.9688
Epoch 4/10
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0496 - accuracy: 0.9840 - val_loss: 0.0659 - val_accuracy: 0.9792
Epoch 5/10
1875/1875 [==============================] - 12s 7ms/step - loss: 0.0474 - accuracy: 0.9846 - val_loss: 0.0107 - val_accuracy: 1.0000
Epoch 6/10
1875/1875 [==============================] - 13s 7ms/step - loss: 0.0477 - accuracy: 0.9845 - val_loss: 0.0030 - val_accuracy: 1.0000
Epoch 7/10
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0457 - accuracy: 0.9848 - val_loss: 0.0244 - val_ac

In [72]:
model5.evaluate(testing_dataset,steps=10)

10/10 [==============================] - 0s 4ms/step - loss: 0.0296 - accuracy: 0.9937


[0.02959929034113884, 0.9937499761581421]